# Generated by Django 3.2.25 on 2026-04-03 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smru', '0002_college_college_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('drive_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='smru.college')),
            ],
            options={
                'verbose_name_plural': 'College Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
