# Generated by Django 3.2.25 on 2026-04-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smru', '0003_collegenote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='college_type',
        ),
    ]
