# Generated by Django 3.2.25 on 2026-04-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smru', '0004_remove_college_college_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('medical', 'Medical')], default='engineering', max_length=20),
        ),
        migrations.AddField(
            model_name='college',
            name='college_type',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('medical', 'Medical')], default='engineering', max_length=20),
        ),
    ]
