# Generated by Django 3.2.25 on 2026-04-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smru', '0006_auto_20260403_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='can_manage_events',
            field=models.BooleanField(default=False, help_text='Allow this user to manage events'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='can_manage_notifications',
            field=models.BooleanField(default=False, help_text='Allow this user to manage notifications'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='can_view_all_complaints',
            field=models.BooleanField(default=False, help_text='Allow this user to view all complaints'),
        ),
    ]
